# Generated by Django 2.1.7 on 2019-04-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuguapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ranked_cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=20)),
                ('kor_lang', models.IntegerField()),
                ('math', models.IntegerField()),
                ('Eng', models.IntegerField()),
                ('science_1', models.IntegerField()),
                ('science_2', models.IntegerField()),
                ('society_1', models.IntegerField()),
                ('society_2', models.IntegerField()),
            ],
        ),
    ]
