# Generated by Django 2.1.7 on 2019-04-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuguapps', '0002_ranked_cut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranked_cut',
            old_name='Eng',
            new_name='grade_cut',
        ),
        migrations.RemoveField(
            model_name='ranked_cut',
            name='kor_lang',
        ),
        migrations.RemoveField(
            model_name='ranked_cut',
            name='math',
        ),
        migrations.RemoveField(
            model_name='ranked_cut',
            name='science_1',
        ),
        migrations.RemoveField(
            model_name='ranked_cut',
            name='science_2',
        ),
        migrations.RemoveField(
            model_name='ranked_cut',
            name='society_1',
        ),
        migrations.RemoveField(
            model_name='ranked_cut',
            name='society_2',
        ),
    ]
