# Generated by Django 2.1.7 on 2019-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuguapps', '0003_auto_20190401_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranked_cut',
            name='grade_cut',
            field=models.FloatField(),
        ),
    ]
