# Generated by Django 2.1.7 on 2019-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuguapps', '0004_auto_20190401_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=20)),
                ('food', models.TextField(default=False)),
                ('sport', models.TextField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
