# Generated by Django 2.1.7 on 2019-04-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuguapps', '0005_auto_20190402_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='stretch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=20)),
                ('action', models.TextField(default=False)),
            ],
        ),
    ]
